version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_oracle_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_oracle_network

  nginx:
    image: nginx:alpine
    container_name: laravel_oracle_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_oracle_network

  oracle:
    image: container-registry.oracle.com/database/express:latest
    container_name: laravel_oracle_db
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - laravel_oracle_network

networks:
  laravel_oracle_network:
    driver: bridge

volumes:
  oracle_data: 